name: Workshop workflow
on: [push]

jobs:
  build:
    name: Add Colab links
    runs-on: ubuntu-latest
    steps:
      - name: Work around permission issue
        run: git config --global --add safe.directory /__w/workshops/workshops
      - name: Checkout first
        id: checkout
        uses: actions/checkout@v2

      - name: Add/Update badges
        id: badges
        uses: trsvchn/colab-badge-action@v3
        with:
          check: 'all'
          update: true
          target_branch: main

      - name: push
        uses: actions-x/commit@v2