name: Workshop workflow
on: [push]

jobs:
  build:
    name: Add Colab links
    runs-on: ubuntu-latest
    steps:
      - name: Trust My Directory
        run: export GIT_CEILING_DIRECTORIES=/__w # only work before git v2.35.2
      - name: Checkout first
        id: checkout
        uses: actions/checkout@v2

      - name: Add/update badges
        id: badges
        uses: trsvchn/colab-badge-action@v4
        with:
          check: 'all'
          update: true
          target_branch: main
          target_repository: huggingface/workshops

      - name: push
        uses: github-actions-x/commit@v2.9